[package]
name = "rust-portal-game"
version = "0.0.0"
edition = "2024"

[dependencies]
bytemuck = "1.23.1"
engine = { version = "0.0.0", path = "../engine", package = "rust-portal-engine" }
glam = { version = "0.30.4", features = ["bytemuck"] }
gltf = { version = "1.4.1", features = ["KHR_lights_punctual"] }
itertools = "0.14.0"
wgpu = "26.0.1"
winit = "0.30.11"
