[package]
name = "portal-game"
version = "0.0.0"
edition = "2024"

[dependencies]
utils = { workspace = true }
pgk = { workspace = true }
engine = { workspace = true }
shader-preprocessor = { workspace = true }

bytemuck = "1.23.1"
crevice = { version = "0.18.0", features = ["glam"] }
glam = { version = "0.30.4", features = ["bytemuck"] }
gltf = { version = "1.4.1", features = ["KHR_lights_punctual"] }
winit = "0.30.11"
