binop_separator = "Front"
brace_style = "SameLineWhere"
condense_wildcard_suffixes = true
control_brace_style = "ClosingNextLine"
empty_item_single_line = true
fn_args_layout = "Compressed"
fn_single_line = true
format_strings = true
imports_indent = "Block"
imports_layout = "HorizontalVertical"
indent_style = "Block"
match_arm_blocks = true
match_block_trailing_comma = false
merge_derives = true
imports_granularity = "Crate"
newline_style = "Unix"
overflow_delimited_expr = true
remove_nested_parens = true
reorder_imports = true
group_imports = "StdExternalCrate"
reorder_modules = true
space_before_colon = false
spaces_around_ranges = false
struct_lit_single_line = true
trailing_comma = "Vertical"
use_field_init_shorthand = true
use_try_shorthand = true
