[package]
name = "portal-ecs"
version = "0.1.0"
edition = "2024"

[dependencies]
utils = { workspace = true }
dynvec = { workspace = true }

derive-where = { version = "1.5.0", features = ["nightly"] }
derive_more = { version = "2.0.1", features = ["from", "into", "is_variant"] }
thiserror = "2.0.16"
variadics_please = "1.1.0"
