[package]
name = "portal-utils"
version = "0.1.0"
edition = "2024"

[dependencies]
derive-where = { version = "1.5.0", features = ["nightly"] }
getset = "0.1.6"
readonly = "0.2.13"
itertools = "0.14.0"
glam = { version = "0.30.4", features = ["bytemuck"] }
sorted-vec = "0.8.8"
dyn-clone = "1.0.20"
either = "1.15.0"
smallvec = { version = "1.15.1", features = ["union", "const_generics", "specialization", "const_new"] }
